### ISSUE TITLE
Prescribing formatting step appears not to run

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing-data#2]
```
$ python runner.py runimporters --paranoid
Traceback (most recent call last):
  File "runner.py", line 397, in <module>
    ImporterRunner().run_all_importers(paranoid=args.paranoid)
  File "runner.py", line 340, in run_all_importers
    for cmd in source.importer_cmds_with_latest_data():
  File "runner.py", line 150, in importer_cmds_with_latest_data
    latest_data = self.most_recent_file(importer)
  File "runner.py", line 128, in most_recent_file
    (file_regex, OPENP_DATA_BASEDIR, self['id']))
StandardError: Couldn't find a file matching T\d+PDPI.*_formatted\.CSV at /Users/anna/gdrive/Clients/ebmdatalab/openprescribing-data/data/prescribing
```

**Comment by sebbacon** [comment]
Unable to reproduce this. Will reopen if/when it happens again.
